### ISSUE TITLE
Provide Dockerfile for kiweeteam/php-cli-shopware-builder

### ISSUE THREAD

**Issue by xetys** [KiweeEu/shopware-kubernetes-dev#3]
Hey,

I couldn't find the Dockerfile of the kiweeteam/php-cli-shopware-builder image, which is used by this project to build further images. I would kindly ask to provide it, or even include it as a build step for the Dockerfile in `docker/Dockerfile`

**Comment by tom00** [comment]
Hi, thanks for reporting!
There was an invalid default alpine version as the default argument value. I've updated it to alpine 3.15.
Here you can find the available images: https://hub.docker.com/r/kiweeteam/php-cli-shopware-builder/tags
